language: node_js
node_js:
  - "6.12"
  - "7.10"
  - "8.9"
matrix:
  include:
    - node_js: "9"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
    - node_js: "10"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    # Allow the nightly installs to fail
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
script:
  - "yarn test"
after_script: "cat ./coverage/lcov.info | coveralls"